version: "3.3"

networks:
  elevenLabs_network:

services:
  node:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: elevenLabs
    ports:
      - 3000:3000
    volumes:
      - .:/workspaces
    networks:
      - elevenLabs_network

  db:
    image: mariadb:10.6.10-focal
    container_name: elevenLabs_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: astronaute
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - elevenLabs_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: elevenLabs_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    volumes:
      - phpmyadmin:/sessions
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - elevenLabs_network

volumes:
  db:
  phpmyadmin:
