version: "3.3"

services:
  node:
    container_name: elevenLabs
    build:
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/elevenLabs

  db:
    image: mariadb:10.6.10-focal
    container_name: elevenLabs_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: astronaute
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: elevenLabs_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    volumes:
      - phpmyadmin:/sessions
    ports:
      - 8080:80
    depends_on:
      - db

volumes:
  db:
  phpmyadmin:
